import type { ReportsFilterOptions } from '../../types';
import type { ReportItem } from './types';

type InteractionsReportMock = {
  filters: ReportsFilterOptions;
  items: ReportItem[];
};

export const interactionsReportMock: InteractionsReportMock = {
  filters: {
    universities: [
      { id: 1, name: 'МГУ им. М.В. Ломоносова' },
      { id: 2, name: 'РАНХиГС' },
      { id: 3, name: 'СПбПУ' },
      { id: 4, name: 'КФУ' },
      { id: 5, name: 'НИУ ВШЭ' },
      { id: 6, name: 'ТГУ' },
      { id: 7, name: 'УрФУ' },
      { id: 8, name: 'СФУ' },
      { id: 9, name: 'ДГТУ' },
      { id: 10, name: 'МФТИ' },
    ],
    programs: [
      {
        id: 1,
        name: 'Технологии распределенного реестра с использованием программных решений от компании Ростелеком',
      },
      { id: 2, name: 'DevOps' },
      { id: 3, name: 'Информационная безопасность' },
      { id: 4, name: 'Анализ данных' },
      { id: 5, name: 'Веб-разработка' },
      { id: 6, name: 'Облачные технологии' },
      { id: 7, name: 'Кибербезопасность' },
      { id: 8, name: 'Искусственный интеллект' },
      { id: 9, name: 'Разработка ПО' },
      { id: 10, name: 'Машинное обучение' },
      { id: 11, name: 'Аналитика данных и методы искусственного интеллекта' },
    ],
    products: [
      { id: 1, name: 'РТК Продукт X' },
      { id: 2, name: 'Basis' },
      { id: 3, name: 'Solar' },
      { id: 4, name: 'Yandex Cloud' },
      { id: 5, name: 'JetBrains' },
      { id: 6, name: 'VK Cloud' },
      { id: 7, name: 'Kaspersky' },
      { id: 8, name: 'СБЕР' },
      { id: 9, name: '1С' },
      { id: 10, name: 'Nvidia' },
    ],
    responsibles: [
      { id: 1, name: 'Иванов И.И.' },
      { id: 2, name: 'Петров П.П.' },
      { id: 3, name: 'Сидоров А.А.' },
      { id: 4, name: 'Кузнецова Е.В.' },
      { id: 5, name: 'Смирнов Д.О.' },
      { id: 6, name: 'Попова М.С.' },
      { id: 7, name: 'Волков Р.Н.' },
      { id: 8, name: 'Лебедев К.А.' },
      { id: 9, name: 'Новикова А.П.' },
      { id: 10, name: 'Макаров В.С.' },
    ],
  },
  items: [
    {
      id: 1,
      university: 'МГУ им. М.В. Ломоносова',
      program:
        'Технологии распределенного реестра с использованием программных решений от компании Ростелеком',
      product: 'РТК Продукт X',
      responsible: 'Иванов И.И.',
      stage: 'Подписание документов',
      status: 'Просрочен',
      healthScore: 28,
      sla: 10,
      licenseStatus: 'Оформляется',
      licenseExpiresAt: null,
      startDate: '01.01.2026',
      daysInProgress: 85,
      students: 120,
      streams: 4,
      applications: 180,
    },
    {
      id: 2,
      university: 'РАНХиГС',
      program: 'DevOps',
      product: 'Basis',
      responsible: 'Петров П.П.',
      stage: 'Обучение преподавателей',
      status: 'Требует внимания',
      healthScore: 54,
      sla: 14,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2026-11-30',
      startDate: '15.01.2026',
      daysInProgress: 72,
      students: 95,
      streams: 3,
      applications: 142,
    },
    {
      id: 3,
      university: 'СПбПУ',
      program: 'Информационная безопасность',
      product: 'Solar',
      responsible: 'Сидоров А.А.',
      stage: 'Ведение занятий',
      status: 'В работе',
      healthScore: 84,
      sla: 30,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-02-28',
      startDate: '03.02.2026',
      daysInProgress: 64,
      students: 86,
      streams: 3,
      applications: 114,
    },
    {
      id: 4,
      university: 'КФУ',
      program: 'Анализ данных',
      product: 'Yandex Cloud',
      responsible: 'Кузнецова Е.В.',
      stage: 'Передача материалов',
      status: 'Требует внимания',
      healthScore: 61,
      sla: 7,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2026-10-15',
      startDate: '17.02.2026',
      daysInProgress: 58,
      students: 74,
      streams: 2,
      applications: 105,
    },
    {
      id: 5,
      university: 'НИУ ВШЭ',
      program: 'Веб-разработка',
      product: 'JetBrains',
      responsible: 'Смирнов Д.О.',
      stage: 'Ведение занятий',
      status: 'Завершён',
      healthScore: 96,
      sla: 30,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-03-31',
      startDate: '05.03.2026',
      daysInProgress: 46,
      students: 132,
      streams: 5,
      applications: 210,
    },
    {
      id: 6,
      university: 'ТГУ',
      program: 'Облачные технологии',
      product: 'VK Cloud',
      responsible: 'Попова М.С.',
      stage: 'Организация встречи',
      status: 'В работе',
      healthScore: 79,
      sla: 5,
      licenseStatus: 'Не требуется',
      licenseExpiresAt: null,
      startDate: '10.03.2026',
      daysInProgress: 41,
      students: 68,
      streams: 2,
      applications: 91,
    },
    {
      id: 7,
      university: 'УрФУ',
      program: 'Кибербезопасность',
      product: 'Kaspersky',
      responsible: 'Волков Р.Н.',
      stage: 'Обучение преподавателей',
      status: 'Требует внимания',
      healthScore: 57,
      sla: 14,
      licenseStatus: 'Истекла',
      licenseExpiresAt: '2026-08-31',
      startDate: '21.03.2026',
      daysInProgress: 39,
      students: 78,
      streams: 3,
      applications: 124,
    },
    {
      id: 8,
      university: 'СФУ',
      program: 'Искусственный интеллект',
      product: 'СБЕР',
      responsible: 'Лебедев К.А.',
      stage: 'Внедрение продукта',
      status: 'В работе',
      healthScore: 87,
      sla: 21,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-04-30',
      startDate: '02.04.2026',
      daysInProgress: 34,
      students: 106,
      streams: 4,
      applications: 156,
    },
    {
      id: 9,
      university: 'ДГТУ',
      program: 'Разработка ПО',
      product: '1С',
      responsible: 'Новикова А.П.',
      stage: 'Подписание документов',
      status: 'Требует внимания',
      healthScore: 48,
      sla: 10,
      licenseStatus: 'Оформляется',
      licenseExpiresAt: null,
      startDate: '14.04.2026',
      daysInProgress: 31,
      students: 62,
      streams: 2,
      applications: 88,
    },
    {
      id: 10,
      university: 'МФТИ',
      program: 'Машинное обучение',
      product: 'Nvidia',
      responsible: 'Макаров В.С.',
      stage: 'Ведение занятий',
      status: 'Завершён',
      healthScore: 94,
      sla: 30,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-05-31',
      startDate: '20.04.2026',
      daysInProgress: 97,
      students: 144,
      streams: 5,
      applications: 230,
    },
    {
      id: 11,
      university: 'МГУ им. М.В. Ломоносова',
      program: 'Информационная безопасность',
      product: 'Solar',
      responsible: 'Иванов И.И.',
      stage: 'Передача материалов',
      status: 'В работе',
      healthScore: 81,
      sla: 7,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-01-31',
      startDate: '05.05.2026',
      daysInProgress: 28,
      students: 91,
      streams: 3,
      applications: 137,
    },
    {
      id: 12,
      university: 'РАНХиГС',
      program: 'Анализ данных',
      product: 'Yandex Cloud',
      responsible: 'Петров П.П.',
      stage: 'Согласование программы',
      status: 'В работе',
      healthScore: 76,
      sla: 10,
      licenseStatus: 'Оформляется',
      licenseExpiresAt: null,
      startDate: '18.05.2026',
      daysInProgress: 24,
      students: 83,
      streams: 3,
      applications: 119,
    },
    {
      id: 13,
      university: 'СПбПУ',
      program: 'DevOps',
      product: 'Basis',
      responsible: 'Сидоров А.А.',
      stage: 'Организация встречи',
      status: 'Просрочен',
      healthScore: 24,
      sla: 5,
      licenseStatus: 'Истекла',
      licenseExpiresAt: '2026-07-31',
      startDate: '03.06.2026',
      daysInProgress: 81,
      students: 76,
      streams: 2,
      applications: 108,
    },
    {
      id: 14,
      university: 'КФУ',
      program: 'Облачные технологии',
      product: 'VK Cloud',
      responsible: 'Кузнецова Е.В.',
      stage: 'Ведение занятий',
      status: 'В работе',
      healthScore: 89,
      sla: 30,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-06-30',
      startDate: '16.06.2026',
      daysInProgress: 22,
      students: 116,
      streams: 4,
      applications: 169,
    },
    {
      id: 15,
      university: 'НИУ ВШЭ',
      program: 'Кибербезопасность',
      product: 'Kaspersky',
      responsible: 'Смирнов Д.О.',
      stage: 'Обучение преподавателей',
      status: 'Требует внимания',
      healthScore: 63,
      sla: 14,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2026-10-10',
      startDate: '01.07.2026',
      daysInProgress: 19,
      students: 88,
      streams: 3,
      applications: 131,
    },
    {
      id: 16,
      university: 'ТГУ',
      program: 'Искусственный интеллект',
      product: 'СБЕР',
      responsible: 'Попова М.С.',
      stage: 'Внедрение продукта',
      status: 'В работе',
      healthScore: 86,
      sla: 21,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-07-31',
      startDate: '12.07.2026',
      daysInProgress: 17,
      students: 97,
      streams: 3,
      applications: 148,
    },
    {
      id: 17,
      university: 'УрФУ',
      program: 'DevOps',
      product: 'Basis',
      responsible: 'Волков Р.Н.',
      stage: 'Передача материалов',
      status: 'В работе',
      healthScore: 82,
      sla: 7,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-01-15',
      startDate: '18.07.2026',
      daysInProgress: 15,
      students: 84,
      streams: 3,
      applications: 126,
    },
    {
      id: 18,
      university: 'СФУ',
      program: 'Информационная безопасность',
      product: 'Solar',
      responsible: 'Лебедев К.А.',
      stage: 'Подписание документов',
      status: 'Требует внимания',
      healthScore: 43,
      sla: 10,
      licenseStatus: 'Оформляется',
      licenseExpiresAt: null,
      startDate: '20.07.2026',
      daysInProgress: 31,
      students: 72,
      streams: 2,
      applications: 108,
    },
    {
      id: 19,
      university: 'ДГТУ',
      program: 'Веб-разработка',
      product: 'JetBrains',
      responsible: 'Новикова А.П.',
      stage: 'Обучение преподавателей',
      status: 'В работе',
      healthScore: 85,
      sla: 14,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-08-31',
      startDate: '25.07.2026',
      daysInProgress: 14,
      students: 96,
      streams: 4,
      applications: 154,
    },
    {
      id: 20,
      university: 'МФТИ',
      program: 'Машинное обучение',
      product: 'Nvidia',
      responsible: 'Макаров В.С.',
      stage: 'Ведение занятий',
      status: 'В работе',
      healthScore: 91,
      sla: 30,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-09-30',
      startDate: '29.07.2026',
      daysInProgress: 12,
      students: 118,
      streams: 4,
      applications: 189,
    },
    {
      id: 21,
      university: 'МГУ им. М.В. Ломоносова',
      program: 'Анализ данных',
      product: 'Yandex Cloud',
      responsible: 'Иванов И.И.',
      stage: 'Организация встречи',
      status: 'Требует внимания',
      healthScore: 52,
      sla: 5,
      licenseStatus: 'Не требуется',
      licenseExpiresAt: null,
      startDate: '01.08.2026',
      daysInProgress: 36,
      students: 89,
      streams: 3,
      applications: 136,
    },
    {
      id: 22,
      university: 'РАНХиГС',
      program: 'Разработка ПО',
      product: '1С',
      responsible: 'Петров П.П.',
      stage: 'Внедрение продукта',
      status: 'В работе',
      healthScore: 88,
      sla: 21,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-03-15',
      startDate: '04.08.2026',
      daysInProgress: 11,
      students: 104,
      streams: 4,
      applications: 162,
    },
    {
      id: 23,
      university: 'СПбПУ',
      program: 'Облачные технологии',
      product: 'VK Cloud',
      responsible: 'Сидоров А.А.',
      stage: 'Согласование программы',
      status: 'Требует внимания',
      healthScore: 59,
      sla: 10,
      licenseStatus: 'Оформляется',
      licenseExpiresAt: null,
      startDate: '07.08.2026',
      daysInProgress: 28,
      students: 91,
      streams: 3,
      applications: 145,
    },
    {
      id: 24,
      university: 'КФУ',
      program: 'Кибербезопасность',
      product: 'Kaspersky',
      responsible: 'Кузнецова Е.В.',
      stage: 'Передача материалов',
      status: 'В работе',
      healthScore: 83,
      sla: 7,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-02-15',
      startDate: '10.08.2026',
      daysInProgress: 10,
      students: 67,
      streams: 2,
      applications: 102,
    },
    {
      id: 25,
      university: 'НИУ ВШЭ',
      program: 'Искусственный интеллект',
      product: 'СБЕР',
      responsible: 'Смирнов Д.О.',
      stage: 'Ведение занятий',
      status: 'Завершён',
      healthScore: 98,
      sla: 30,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-12-31',
      startDate: '12.08.2026',
      daysInProgress: 93,
      students: 156,
      streams: 6,
      applications: 248,
    },
    {
      id: 26,
      university: 'ТГУ',
      program: 'Веб-разработка',
      product: 'JetBrains',
      responsible: 'Попова М.С.',
      stage: 'Обучение преподавателей',
      status: 'В работе',
      healthScore: 80,
      sla: 14,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-06-15',
      startDate: '14.08.2026',
      daysInProgress: 9,
      students: 73,
      streams: 3,
      applications: 117,
    },
    {
      id: 27,
      university: 'УрФУ',
      program: 'Машинное обучение',
      product: 'Nvidia',
      responsible: 'Волков Р.Н.',
      stage: 'Внедрение продукта',
      status: 'Просрочен',
      healthScore: 31,
      sla: 21,
      licenseStatus: 'Истекла',
      licenseExpiresAt: '2026-09-01',
      startDate: '16.08.2026',
      daysInProgress: 49,
      students: 102,
      streams: 4,
      applications: 164,
    },
    {
      id: 28,
      university: 'СФУ',
      program: 'Анализ данных',
      product: 'Yandex Cloud',
      responsible: 'Лебедев К.А.',
      stage: 'Согласование программы',
      status: 'В работе',
      healthScore: 78,
      sla: 10,
      licenseStatus: 'Не требуется',
      licenseExpiresAt: null,
      startDate: '18.08.2026',
      daysInProgress: 8,
      students: 81,
      streams: 3,
      applications: 123,
    },
    {
      id: 29,
      university: 'ДГТУ',
      program: 'Информационная безопасность',
      product: 'Solar',
      responsible: 'Новикова А.П.',
      stage: 'Организация встречи',
      status: 'Требует внимания',
      healthScore: 46,
      sla: 5,
      licenseStatus: 'Оформляется',
      licenseExpiresAt: null,
      startDate: '20.08.2026',
      daysInProgress: 26,
      students: 69,
      streams: 2,
      applications: 98,
    },
    {
      id: 30,
      university: 'МФТИ',
      program: 'DevOps',
      product: 'Basis',
      responsible: 'Макаров В.С.',
      stage: 'Передача материалов',
      status: 'В работе',
      healthScore: 90,
      sla: 7,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-08-31',
      startDate: '22.08.2026',
      daysInProgress: 7,
      students: 112,
      streams: 4,
      applications: 171,
    },
    {
      id: 31,
      university: 'МФТИ',
      program: 'Devops инженер (работа с технологической платформой "Базис")',
      product: 'Basis',
      responsible: 'Макаров В.С.',
      stage: 'Передача материалов',
      status: 'В работе',
      healthScore: 90,
      sla: 7,
      licenseStatus: 'Активна',
      licenseExpiresAt: '2027-09-30',
      startDate: '19.09.2026',
      daysInProgress: 5,
      students: 112,
      streams: 1,
      applications: 60,
    },
  ],
};

