import type { ProgramsReportMock } from './types';

type ImplementationStatus = 'implemented' | 'inProgress';

const universities = [
  { id: 1, name: 'РЭУ' },
  { id: 2, name: 'РАНХиГС' },
  { id: 3, name: 'Станкин' },
  { id: 4, name: 'СГТУ' },
  { id: 5, name: 'Сеченовский университет' },
  { id: 6, name: 'Томский политех' },
  { id: 7, name: 'Чеченский государственный университет' },
  { id: 8, name: 'Тюменский университет' },
  { id: 9, name: 'Тульский ГУ' },
  { id: 10, name: 'ТГУ' },
  { id: 11, name: 'СКГА' },
  { id: 12, name: 'Самарский политех' },
  { id: 13, name: 'НВГУ' },
  { id: 14, name: 'МЭИ' },
  { id: 15, name: 'МФТИ' },
  { id: 16, name: 'КФУ' },
  { id: 17, name: 'КАИ' },
  { id: 18, name: 'ГУ' },
  {
    id: 19,
    name: 'Волгоградский государственный технический университет',
  },
  { id: 20, name: 'МГУ' },
  { id: 21, name: 'НИУ ВШЭ' },
  { id: 22, name: 'ИТМО' },
];

const programs = [
  {
    id: 1,
    name: 'Основы UX/UI-дизайна',
  },
  {
    id: 2,
    name: 'Python-разработчик с использованием инструментов ИИ',
  },
  {
    id: 3,
    name: 'Графический дизайн пользовательских интерфейсов',
  },
  {
    id: 4,
    name: 'Введение в информационную безопасность',
  },
  {
    id: 5,
    name: 'Инженер-тестировщик',
  },
  {
    id: 6,
    name: 'DevOps-инженер с нуля',
  },
  {
    id: 7,
    name: 'Анализ данных без программирования',
  },
  {
    id: 8,
    name: 'Веб-разработка на платформе «Акола»',
  },
  {
    id: 9,
    name: 'Промпт-инжиниринг',
  },
  {
    id: 10,
    name: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
  },
  {
    id: 11,
    name: 'Специалист по анализу данных',
  },
  {
    id: 12,
    name: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
  },
  {
    id: 13,
    name: 'DevOps инженер (работа с технологической платформой «Базис»)',
  },
  {
    id: 14,
    name: 'Аналитика данных и методы искусственного интеллекта',
  },
  {
    id: 15,
    name: 'Анализ данных в Low-code платформах',
  },
  {
    id: 16,
    name: 'Технологии распределенного реестра (для преподавателей)',
  },
  {
    id: 17,
    name: 'Технологии распределенного реестра с использованием программных решений от компании Ростелеком',
  },
  {
    id: 18,
    name: 'Искусственный Интеллект. Применение',
  },
  {
    id: 19,
    name: 'Искусственный Интеллект. Базовые навыки',
  },
  {
    id: 20,
    name: 'SQL разработчик (вводный курс)',
  },
  {
    id: 21,
    name: 'Аналитика данных на Python',
  },
  {
    id: 22,
    name: 'Введение в аналитику данных',
  },
];

const products = [
  {
    id: 1,
    name: 'Базис',
  },
  {
    id: 2,
    name: 'TData',
  },
  {
    id: 3,
    name: 'Solar',
  },
  {
    id: 4,
    name: 'Ростелеком Ключ',
  },
  {
    id: 5,
    name: 'Акола',
  },
  {
    id: 6,
    name: 'Аврора',
  },
  {
    id: 7,
    name: 'ИИ-платформа',
  },
  {
    id: 8,
    name: 'Low-code платформа',
  },
  {
    id: 9,
    name: 'Платформа распределенного реестра',
  },
  {
    id: 10,
    name: 'Без привязки к ИТ-продукту',
  },
];

const responsibles = [
  {
    id: 1,
    name: 'Иван Иванов',
  },
  {
    id: 2,
    name: 'Мария Смирнова',
  },
  {
    id: 3,
    name: 'Анна Петрова',
  },
  {
    id: 4,
    name: 'Алексей Соколов',
  },
  {
    id: 5,
    name: 'Елена Кузнецова',
  },
  {
    id: 6,
    name: 'Дмитрий Волков',
  },
];

const getById = <T extends { id: number }>(items: T[], id: number): T => {
  const item = items.find((item) => item.id === id);

  if (!item) {
    throw new Error(`Mock entity with id=${id} not found`);
  }

  return item;
};

const createMetric = ({
  id,
  date,
  universityId,
  responsibleId,
  programId,
  productId,
  applications,
  students,
  streams,
  implementationStatus,
}: {
  id: number;
  date: string;
  universityId: number;
  responsibleId: number;
  programId: number;
  productId: number;
  applications: number;
  students: number;
  streams: number;
  implementationStatus: ImplementationStatus;
}) => {
  const university = getById(universities, universityId);
  const responsible = getById(responsibles, responsibleId);
  const program = getById(programs, programId);
  const product = getById(products, productId);

  return {
    id,
    date,
    university,
    responsible,
    programId: program.id,
    program: program.name,
    productId: product.id,
    product: product.name,
    applications,
    students,
    streams,
    implementationStatus,
  };
};

export const programsReportMock: ProgramsReportMock = {
  filters: {
    universities,
    programs,
    products,
    responsibles,
  },

  metrics: [
    createMetric({
      id: 1,
      date: '2025-10-14',
      universityId: 1,
      responsibleId: 1,
      programId: 1,
      productId: 10,
      applications: 92,
      students: 47,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 2,
      date: '2026-02-18',
      universityId: 8,
      responsibleId: 4,
      programId: 1,
      productId: 10,
      applications: 68,
      students: 34,
      streams: 2,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 3,
      date: '2025-11-08',
      universityId: 15,
      responsibleId: 1,
      programId: 2,
      productId: 7,
      applications: 164,
      students: 89,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 4,
      date: '2026-03-21',
      universityId: 21,
      responsibleId: 2,
      programId: 2,
      productId: 7,
      applications: 148,
      students: 76,
      streams: 4,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 5,
      date: '2026-01-11',
      universityId: 4,
      responsibleId: 3,
      programId: 3,
      productId: 10,
      applications: 73,
      students: 38,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 6,
      date: '2026-06-09',
      universityId: 12,
      responsibleId: 5,
      programId: 3,
      productId: 10,
      applications: 61,
      students: 29,
      streams: 1,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 7,
      date: '2025-12-03',
      universityId: 14,
      responsibleId: 3,
      programId: 4,
      productId: 3,
      applications: 134,
      students: 72,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 8,
      date: '2026-04-17',
      universityId: 5,
      responsibleId: 2,
      programId: 4,
      productId: 3,
      applications: 105,
      students: 56,
      streams: 3,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 9,
      date: '2026-02-01',
      universityId: 3,
      responsibleId: 1,
      programId: 5,
      productId: 10,
      applications: 116,
      students: 63,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 10,
      date: '2026-07-22',
      universityId: 9,
      responsibleId: 6,
      programId: 5,
      productId: 10,
      applications: 87,
      students: 42,
      streams: 2,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 11,
      date: '2025-10-28',
      universityId: 6,
      responsibleId: 4,
      programId: 6,
      productId: 1,
      applications: 183,
      students: 102,
      streams: 5,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 12,
      date: '2026-01-15',
      universityId: 20,
      responsibleId: 1,
      programId: 6,
      productId: 1,
      applications: 151,
      students: 84,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 13,
      date: '2026-05-19',
      universityId: 15,
      responsibleId: 1,
      programId: 6,
      productId: 1,
      applications: 128,
      students: 69,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 14,
      date: '2026-09-03',
      universityId: 22,
      responsibleId: 5,
      programId: 6,
      productId: 1,
      applications: 143,
      students: 75,
      streams: 4,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 15,
      date: '2026-01-26',
      universityId: 2,
      responsibleId: 2,
      programId: 7,
      productId: 2,
      applications: 122,
      students: 67,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 16,
      date: '2026-06-13',
      universityId: 13,
      responsibleId: 6,
      programId: 7,
      productId: 2,
      applications: 94,
      students: 48,
      streams: 2,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 17,
      date: '2025-11-17',
      universityId: 17,
      responsibleId: 4,
      programId: 8,
      productId: 5,
      applications: 78,
      students: 39,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 18,
      date: '2026-04-07',
      universityId: 10,
      responsibleId: 5,
      programId: 8,
      productId: 5,
      applications: 103,
      students: 54,
      streams: 3,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 19,
      date: '2026-02-14',
      universityId: 21,
      responsibleId: 2,
      programId: 9,
      productId: 7,
      applications: 201,
      students: 118,
      streams: 5,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 20,
      date: '2026-08-05',
      universityId: 1,
      responsibleId: 1,
      programId: 9,
      productId: 7,
      applications: 176,
      students: 94,
      streams: 4,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 21,
      date: '2026-01-08',
      universityId: 16,
      responsibleId: 3,
      programId: 10,
      productId: 6,
      applications: 69,
      students: 32,
      streams: 2,
      implementationStatus: 'inProgress',
    }),
    createMetric({
      id: 22,
      date: '2026-05-27',
      universityId: 7,
      responsibleId: 6,
      programId: 10,
      productId: 6,
      applications: 81,
      students: 43,
      streams: 2,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 23,
      date: '2025-12-16',
      universityId: 21,
      responsibleId: 2,
      programId: 11,
      productId: 2,
      applications: 187,
      students: 101,
      streams: 5,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 24,
      date: '2026-03-12',
      universityId: 22,
      responsibleId: 5,
      programId: 11,
      productId: 2,
      applications: 169,
      students: 91,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 25,
      date: '2026-07-14',
      universityId: 6,
      responsibleId: 4,
      programId: 11,
      productId: 2,
      applications: 132,
      students: 74,
      streams: 3,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 26,
      date: '2026-01-19',
      universityId: 2,
      responsibleId: 2,
      programId: 12,
      productId: 4,
      applications: 108,
      students: 59,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 27,
      date: '2026-04-23',
      universityId: 14,
      responsibleId: 3,
      programId: 12,
      productId: 4,
      applications: 91,
      students: 46,
      streams: 2,
      implementationStatus: 'inProgress',
    }),
    createMetric({
      id: 28,
      date: '2026-08-11',
      universityId: 19,
      responsibleId: 6,
      programId: 12,
      productId: 4,
      applications: 97,
      students: 51,
      streams: 3,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 29,
      date: '2025-11-24',
      universityId: 3,
      responsibleId: 1,
      programId: 13,
      productId: 1,
      applications: 156,
      students: 85,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 30,
      date: '2026-03-29',
      universityId: 12,
      responsibleId: 5,
      programId: 13,
      productId: 1,
      applications: 119,
      students: 62,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 31,
      date: '2026-09-08',
      universityId: 17,
      responsibleId: 4,
      programId: 13,
      productId: 1,
      applications: 127,
      students: 68,
      streams: 3,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 32,
      date: '2025-10-09',
      universityId: 15,
      responsibleId: 1,
      programId: 14,
      productId: 7,
      applications: 214,
      students: 126,
      streams: 6,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 33,
      date: '2026-02-25',
      universityId: 21,
      responsibleId: 2,
      programId: 14,
      productId: 7,
      applications: 198,
      students: 114,
      streams: 5,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 34,
      date: '2026-07-03',
      universityId: 10,
      responsibleId: 4,
      programId: 14,
      productId: 7,
      applications: 144,
      students: 79,
      streams: 4,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 35,
      date: '2026-01-31',
      universityId: 8,
      responsibleId: 4,
      programId: 15,
      productId: 8,
      applications: 86,
      students: 44,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 36,
      date: '2026-06-20',
      universityId: 18,
      responsibleId: 6,
      programId: 15,
      productId: 8,
      applications: 75,
      students: 38,
      streams: 2,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 37,
      date: '2025-12-09',
      universityId: 5,
      responsibleId: 3,
      programId: 16,
      productId: 9,
      applications: 63,
      students: 41,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 38,
      date: '2026-04-12',
      universityId: 16,
      responsibleId: 5,
      programId: 16,
      productId: 9,
      applications: 71,
      students: 45,
      streams: 2,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 39,
      date: '2026-02-08',
      universityId: 6,
      responsibleId: 4,
      programId: 17,
      productId: 9,
      applications: 84,
      students: 49,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 40,
      date: '2026-08-18',
      universityId: 14,
      responsibleId: 3,
      programId: 17,
      productId: 9,
      applications: 77,
      students: 42,
      streams: 2,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 41,
      date: '2025-11-05',
      universityId: 20,
      responsibleId: 1,
      programId: 18,
      productId: 7,
      applications: 172,
      students: 93,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 42,
      date: '2026-05-05',
      universityId: 22,
      responsibleId: 5,
      programId: 18,
      productId: 7,
      applications: 161,
      students: 88,
      streams: 4,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 43,
      date: '2026-01-05',
      universityId: 7,
      responsibleId: 6,
      programId: 19,
      productId: 7,
      applications: 137,
      students: 81,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 44,
      date: '2026-07-29',
      universityId: 9,
      responsibleId: 6,
      programId: 19,
      productId: 7,
      applications: 118,
      students: 67,
      streams: 3,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 45,
      date: '2025-10-21',
      universityId: 3,
      responsibleId: 1,
      programId: 20,
      productId: 2,
      applications: 145,
      students: 79,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 46,
      date: '2026-03-06',
      universityId: 13,
      responsibleId: 6,
      programId: 20,
      productId: 2,
      applications: 121,
      students: 64,
      streams: 3,
      implementationStatus: 'implemented',
    }),

    createMetric({
      id: 47,
      date: '2025-12-21',
      universityId: 15,
      responsibleId: 1,
      programId: 21,
      productId: 2,
      applications: 191,
      students: 109,
      streams: 5,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 48,
      date: '2026-04-28',
      universityId: 21,
      responsibleId: 2,
      programId: 21,
      productId: 2,
      applications: 173,
      students: 96,
      streams: 4,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 49,
      date: '2026-09-12',
      universityId: 1,
      responsibleId: 1,
      programId: 21,
      productId: 2,
      applications: 139,
      students: 76,
      streams: 3,
      implementationStatus: 'inProgress',
    }),

    createMetric({
      id: 50,
      date: '2026-02-19',
      universityId: 11,
      responsibleId: 4,
      programId: 22,
      productId: 2,
      applications: 111,
      students: 61,
      streams: 3,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 51,
      date: '2026-06-02',
      universityId: 19,
      responsibleId: 6,
      programId: 22,
      productId: 2,
      applications: 96,
      students: 52,
      streams: 2,
      implementationStatus: 'implemented',
    }),
    createMetric({
      id: 52,
      date: '2026-09-16',
      universityId: 16,
      responsibleId: 5,
      programId: 22,
      productId: 2,
      applications: 104,
      students: 57,
      streams: 3,
      implementationStatus: 'inProgress',
    }),
  ],
};
