import type { ManagerOrganizationHealthItem } from '../../types';

export const managerOrganizationsHealthMock: ManagerOrganizationHealthItem[] = [
  {
    organizationId: 1,
    organizationName: 'ЮФУ',
    kamId: 1,
    kamName: 'Анна Ковалёва',
    programsCount: 2,
    healthScore: 38,
    healthStatus: 'critical',
  },
  {
    organizationId: 2,
    organizationName: 'МГТУ',
    kamId: 1,
    kamName: 'Анна Ковалёва',
    programsCount: 2,
    healthScore: 41,
    healthStatus: 'critical',
  },
  {
    organizationId: 3,
    organizationName: 'СПбПУ',
    kamId: 2,
    kamName: 'Борис Ильин',
    programsCount: 1,
    healthScore: 44,
    healthStatus: 'warning',
  },
  {
    organizationId: 4,
    organizationName: 'УрФУ',
    kamId: 2,
    kamName: 'Борис Ильин',
    programsCount: 2,
    healthScore: 58,
    healthStatus: 'warning',
  },
  {
    organizationId: 5,
    organizationName: 'РАНХиГС',
    kamId: 3,
    kamName: 'Мария Соколова',
    programsCount: 1,
    healthScore: 81,
    healthStatus: 'healthy',
  },
  {
    organizationId: 6,
    organizationName: 'ИТМО',
    kamId: 3,
    kamName: 'Мария Соколова',
    programsCount: 2,
    healthScore: 86,
    healthStatus: 'healthy',
  },
];
