import type { ManagerLoadItem } from '../../types';

export const managerLoadMock: ManagerLoadItem[] = [
  {
    id: 1,
    name: 'Анна Ковалёва',
    programsCount: 11,
    redProgramsCount: 3,
    overdueTasksCount: 2,
    criticalTasksCount: 5,
  },
  {
    id: 2,
    name: 'Борис Ильин',
    programsCount: 9,
    redProgramsCount: 1,
    overdueTasksCount: 1,
    criticalTasksCount: 4,
  },
  {
    id: 3,
    name: 'Мария Соколова',
    programsCount: 8,
    redProgramsCount: 1,
    overdueTasksCount: 0,
    criticalTasksCount: 2,
  },
  {
    id: 4,
    name: 'Дмитрий Волков',
    programsCount: 13,
    redProgramsCount: 4,
    overdueTasksCount: 3,
    criticalTasksCount: 6,
  },
  {
    id: 5,
    name: 'Елена Морозова',
    programsCount: 7,
    redProgramsCount: 0,
    overdueTasksCount: 1,
    criticalTasksCount: 1,
  },
  {
    id: 6,
    name: 'Алексей Петров',
    programsCount: 10,
    redProgramsCount: 2,
    overdueTasksCount: 4,
    criticalTasksCount: 3,
  },
  {
    id: 7,
    name: 'Ольга Смирнова',
    programsCount: 6,
    redProgramsCount: 1,
    overdueTasksCount: 0,
    criticalTasksCount: 1,
  },
  {
    id: 8,
    name: 'Илья Кузнецов',
    programsCount: 12,
    redProgramsCount: 2,
    overdueTasksCount: 2,
    criticalTasksCount: 4,
  },
  {
    id: 9,
    name: 'Наталья Фёдорова',
    programsCount: 5,
    redProgramsCount: 0,
    overdueTasksCount: 0,
    criticalTasksCount: 0,
  },
  {
    id: 10,
    name: 'Сергей Орлов',
    programsCount: 14,
    redProgramsCount: 5,
    overdueTasksCount: 6,
    criticalTasksCount: 7,
  },
  {
    id: 11,
    name: 'Анастасия Лебедева',
    programsCount: 9,
    redProgramsCount: 2,
    overdueTasksCount: 1,
    criticalTasksCount: 3,
  },
  {
    id: 12,
    name: 'Максим Новиков',
    programsCount: 4,
    redProgramsCount: 0,
    overdueTasksCount: 1,
    criticalTasksCount: 1,
  },
];
