import type { DashboardAttentionItem } from './types';

export const dashboardAttentionMock: DashboardAttentionItem[] = [
  {
    id: 1,
    university: 'МГТУ им. Н.Э. Баумана',
    program: 'DevOps',
    stage: 'Обмен документами',
    reason: 'Просрочка предоставления документов',
    days: 14,
    status: 'critical',
  },
  {
    id: 2,
    university: 'СПбГУ',
    program: 'Java',
    stage: 'Обучение преподавателей',
    reason: 'Не завершено обучение',
    days: 8,
    status: 'high',
  },
  {
    id: 3,
    university: 'НГУ',
    program: 'QA',
    stage: 'Лицензия',
    reason: 'Истекает срок лицензии',
    days: 6,
    status: 'high',
  },
  {
    id: 4,
    university: 'КФУ',
    program: 'Data Science',
    stage: 'Контроль исполнения',
    reason: 'Нет активности более 30 дней',
    days: 32,
    status: 'attention',
  },
  {
    id: 5,
    university: 'УрФУ',
    program: 'Frontend',
    stage: 'Подписание',
    reason: 'Не подписан договор',
    days: 10,
    status: 'attention',
  },
  {
    id: 6,
    university: 'НИУ ВШЭ',
    program: 'DevOps',
    stage: 'Передача материалов',
    reason: 'Задержка передачи материалов',
    days: 12,
    status: 'high',
  },
  {
    id: 7,
    university: 'РАНХиГС',
    program: 'Аналитика данных',
    stage: 'Организация встречи',
    reason: 'Нет ответа от вуза',
    days: 18,
    status: 'high',
  },
  {
    id: 8,
    university: 'Томский политех',
    program: 'Java',
    stage: 'Внедрение продукта',
    reason: 'Проблемы с ИТ-инфраструктурой',
    days: 9,
    status: 'attention',
  },
];
