import type { DashboardAttentionResponse } from './types';

export const dashboardAttentionMock: DashboardAttentionResponse = {
  attention: [
    {
      id: 1,
      university: 'РЭУ',
      program: 'DevOps-инженер с нуля',
      stage: 'Обмен документами',
      reason: 'Просрочка предоставления документов',
      days: 14,
      status: {
        code: 'critical',
        label: 'Критический',
        priority: 3,
      },
    },
    {
      id: 2,
      university: 'РАНХиГС',
      program: 'Python-разработчик с использованием инструментов ИИ',
      stage: 'Обучение преподавателей',
      reason: 'Не завершено обучение преподавателей',
      days: 8,
      status: {
        code: 'high',
        label: 'Высокий',
        priority: 2,
      },
    },
    {
      id: 3,
      university: 'Станкин',
      program: 'Введение в информационную безопасность',
      stage: 'Лицензия',
      reason: 'Истекает срок лицензии',
      days: 6,
      status: {
        code: 'high',
        label: 'Высокий',
        priority: 2,
      },
    },
    {
      id: 4,
      university: 'СГТУ',
      program: 'Специалист по анализу данных',
      stage: 'Контроль исполнения',
      reason: 'Нет активности более 30 дней',
      days: 32,
      status: {
        code: 'attention',
        label: 'Требует внимания',
        priority: 1,
      },
    },
    {
      id: 5,
      university: 'Сеченовский',
      program: 'Инженер-тестировщик',
      stage: 'Подписание',
      reason: 'Не подписан договор',
      days: 10,
      status: {
        code: 'attention',
        label: 'Требует внимания',
        priority: 1,
      },
    },
    {
      id: 6,
      university: 'Томский политех',
      program: 'Веб-разработка на платформе «Акола»',
      stage: 'Передача материалов',
      reason: 'Задержка передачи учебных материалов',
      days: 12,
      status: {
        code: 'high',
        label: 'Высокий',
        priority: 2,
      },
    },
    {
      id: 7,
      university: 'КФУ',
      program: 'Промпт-инжиниринг',
      stage: 'Организация встречи',
      reason: 'Нет ответа от вуза',
      days: 18,
      status: {
        code: 'high',
        label: 'Высокий',
        priority: 2,
      },
    },
    {
      id: 8,
      university: 'МФТИ',
      program: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
      stage: 'Внедрение продукта',
      reason: 'Не завершена настройка ИТ-инфраструктуры',
      days: 9,
      status: {
        code: 'attention',
        label: 'Требует внимания',
        priority: 1,
      },
    },
  ],
};
