import type { ManagerReportItem } from './types';

export const managerReportMock: ManagerReportItem[] = [
  {
    id: 1,
    kamId: 1,
    kam: 'Иванов И.И.',
    programs: 3,
    activeInteractions: 3,
    completedInteractions: 2,
    overdueInteractions: 2,
    attentionRequired: 2,
    averageStageDuration: 5.4,
    programItems: [
      {
        id: 1,
        name: 'Python-разработчик с использованием инструментов ИИ',
        product: 'Ростелеком Лицей',
      },
      {
        id: 2,
        name: 'Введение в информационную безопасность',
        product: 'Solar',
      },
      {
        id: 3,
        name: 'DevOps-инженер с нуля',
        product: 'Cloud.ru',
      },
    ],
    activeInteractionItems: [
      {
        id: 1,
        university: 'МГУ им. М.В. Ломоносова',
        program: 'Python-разработчик с использованием инструментов ИИ',
        stage: 'Обмен документами',
      },
      {
        id: 2,
        university: 'МГТУ им. Н.Э. Баумана',
        program: 'Введение в информационную безопасность',
        stage: 'Организация встречи',
      },
      {
        id: 3,
        university: 'НИУ ВШЭ',
        program: 'DevOps-инженер с нуля',
        stage: 'Внедрение продукта',
      },
    ],
    completedInteractionItems: [
      {
        id: 4,
        university: 'СПбГУ',
        program: 'Введение в информационную безопасность',
        stage: 'Ведение занятий',
      },
      {
        id: 5,
        university: 'ИТМО',
        program: 'DevOps-инженер с нуля',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 1,
        university: 'МГТУ им. Н.Э. Баумана',
        program: 'Введение в информационную безопасность',
        stage: 'Организация встречи',
        overdueDays: 4,
      },
      {
        id: 2,
        university: 'НИУ ВШЭ',
        program: 'DevOps-инженер с нуля',
        stage: 'Внедрение продукта',
        overdueDays: 7,
      },
    ],
    attentionItems: [
      {
        id: 1,
        university: 'МГТУ им. Н.Э. Баумана',
        program: 'Введение в информационную безопасность',
        reason: 'Этап просрочен на 4 дня',
      },
      {
        id: 2,
        university: 'НИУ ВШЭ',
        program: 'DevOps-инженер с нуля',
        reason: 'Нет активности более 7 дней',
      },
    ],
  },
  {
    id: 2,
    kamId: 2,
    kam: 'Петров П.П.',
    programs: 3,
    activeInteractions: 2,
    completedInteractions: 3,
    overdueInteractions: 1,
    attentionRequired: 1,
    averageStageDuration: 4.1,
    programItems: [
      {
        id: 4,
        name: 'Основы UX/UI-дизайна',
        product: 'Ростелеком Образование',
      },
      {
        id: 5,
        name: 'Графический дизайн пользовательских интерфейсов',
        product: 'Ростелеком Образование',
      },
      {
        id: 6,
        name: 'Промпт-инжиниринг',
        product: 'GigaChat',
      },
    ],
    activeInteractionItems: [
      {
        id: 6,
        university: 'КФУ',
        program: 'Основы UX/UI-дизайна',
        stage: 'Первичная коммуникация',
      },
      {
        id: 7,
        university: 'УрФУ',
        program: 'Промпт-инжиниринг',
        stage: 'Передача материалов',
      },
    ],
    completedInteractionItems: [
      {
        id: 8,
        university: 'РАНХиГС',
        program: 'Основы UX/UI-дизайна',
        stage: 'Ведение занятий',
      },
      {
        id: 9,
        university: 'СПбПУ',
        program: 'Графический дизайн пользовательских интерфейсов',
        stage: 'Ведение занятий',
      },
      {
        id: 10,
        university: 'ДВФУ',
        program: 'Промпт-инжиниринг',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 3,
        university: 'УрФУ',
        program: 'Промпт-инжиниринг',
        stage: 'Передача материалов',
        overdueDays: 3,
      },
    ],
    attentionItems: [
      {
        id: 3,
        university: 'УрФУ',
        program: 'Промпт-инжиниринг',
        reason: 'Срок передачи материалов истёк',
      },
    ],
  },
  {
    id: 3,
    kamId: 3,
    kam: 'Сидоров А.А.',
    programs: 4,
    activeInteractions: 4,
    completedInteractions: 2,
    overdueInteractions: 3,
    attentionRequired: 3,
    averageStageDuration: 6.8,
    programItems: [
      {
        id: 7,
        name: 'Инженер-тестировщик',
        product: 'Ростелеком ИТ',
      },
      {
        id: 8,
        name: 'Анализ данных без программирования',
        product: 'Data Platform',
      },
      {
        id: 9,
        name: 'Специалист по анализу данных',
        product: 'Data Platform',
      },
      {
        id: 10,
        name: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        product: 'Ростелеком ИТ',
      },
    ],
    activeInteractionItems: [
      {
        id: 11,
        university: 'НГУ',
        program: 'Инженер-тестировщик',
        stage: 'Подписание документов',
      },
      {
        id: 12,
        university: 'ТПУ',
        program: 'Анализ данных без программирования',
        stage: 'Обмен документами',
      },
      {
        id: 13,
        university: 'ТГУ',
        program: 'Специалист по анализу данных',
        stage: 'Актуализация программы',
      },
      {
        id: 14,
        university: 'МИФИ',
        program: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        stage: 'Организация встречи',
      },
    ],
    completedInteractionItems: [
      {
        id: 15,
        university: 'СФУ',
        program: 'Инженер-тестировщик',
        stage: 'Ведение занятий',
      },
      {
        id: 16,
        university: 'ЮФУ',
        program: 'Анализ данных без программирования',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 4,
        university: 'ТПУ',
        program: 'Анализ данных без программирования',
        stage: 'Обмен документами',
        overdueDays: 5,
      },
      {
        id: 5,
        university: 'ТГУ',
        program: 'Специалист по анализу данных',
        stage: 'Актуализация программы',
        overdueDays: 8,
      },
      {
        id: 6,
        university: 'МИФИ',
        program: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        stage: 'Организация встречи',
        overdueDays: 2,
      },
    ],
    attentionItems: [
      {
        id: 4,
        university: 'ТПУ',
        program: 'Анализ данных без программирования',
        reason: 'Документы не согласованы в срок',
      },
      {
        id: 5,
        university: 'ТГУ',
        program: 'Специалист по анализу данных',
        reason: 'Этап просрочен на 8 дней',
      },
      {
        id: 6,
        university: 'МИФИ',
        program: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        reason: 'Не назначена дата следующей встречи',
      },
    ],
  },
  {
    id: 4,
    kamId: 4,
    kam: 'Кузнецова Е.В.',
    programs: 2,
    activeInteractions: 2,
    completedInteractions: 3,
    overdueInteractions: 0,
    attentionRequired: 1,
    averageStageDuration: 3.9,
    programItems: [
      {
        id: 11,
        name: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        product: 'Аврора',
      },
      {
        id: 12,
        name: 'Веб-разработка на платформе «Акола»',
        product: 'Акола',
      },
    ],
    activeInteractionItems: [
      {
        id: 17,
        university: 'ИТМО',
        program: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        stage: 'Обучение преподавателей',
      },
      {
        id: 18,
        university: 'СПбГУТ',
        program: 'Веб-разработка на платформе «Акола»',
        stage: 'Внедрение продукта',
      },
    ],
    completedInteractionItems: [
      {
        id: 19,
        university: 'СПбПУ',
        program: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        stage: 'Ведение занятий',
      },
      {
        id: 20,
        university: 'ГУАП',
        program: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        stage: 'Ведение занятий',
      },
      {
        id: 21,
        university: 'ЛЭТИ',
        program: 'Веб-разработка на платформе «Акола»',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [],
    attentionItems: [
      {
        id: 7,
        university: 'СПбГУТ',
        program: 'Веб-разработка на платформе «Акола»',
        reason: 'Нет активности в течение 5 дней',
      },
    ],
  },
  {
    id: 5,
    kamId: 5,
    kam: 'Смирнов Д.О.',
    programs: 3,
    activeInteractions: 3,
    completedInteractions: 2,
    overdueInteractions: 2,
    attentionRequired: 3,
    averageStageDuration: 5.9,
    programItems: [
      {
        id: 13,
        name: 'DevOps-инженер с нуля',
        product: 'Cloud.ru',
      },
      {
        id: 14,
        name: 'Введение в информационную безопасность',
        product: 'Solar',
      },
      {
        id: 15,
        name: 'Инженер-тестировщик',
        product: 'Ростелеком ИТ',
      },
    ],
    activeInteractionItems: [
      {
        id: 22,
        university: 'ПНИПУ',
        program: 'DevOps-инженер с нуля',
        stage: 'Внедрение продукта',
      },
      {
        id: 23,
        university: 'Самарский университет',
        program: 'Введение в информационную безопасность',
        stage: 'Подписание документов',
      },
      {
        id: 24,
        university: 'ОмГТУ',
        program: 'Инженер-тестировщик',
        stage: 'Передача материалов',
      },
    ],
    completedInteractionItems: [
      {
        id: 25,
        university: 'УрФУ',
        program: 'DevOps-инженер с нуля',
        stage: 'Ведение занятий',
      },
      {
        id: 26,
        university: 'ПГНИУ',
        program: 'Введение в информационную безопасность',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 7,
        university: 'ПНИПУ',
        program: 'DevOps-инженер с нуля',
        stage: 'Внедрение продукта',
        overdueDays: 6,
      },
      {
        id: 8,
        university: 'ОмГТУ',
        program: 'Инженер-тестировщик',
        stage: 'Передача материалов',
        overdueDays: 4,
      },
    ],
    attentionItems: [
      {
        id: 8,
        university: 'ПНИПУ',
        program: 'DevOps-инженер с нуля',
        reason: 'Этап внедрения просрочен',
      },
      {
        id: 9,
        university: 'Самарский университет',
        program: 'Введение в информационную безопасность',
        reason: 'Ожидается подписание документов',
      },
      {
        id: 10,
        university: 'ОмГТУ',
        program: 'Инженер-тестировщик',
        reason: 'Материалы не переданы в срок',
      },
    ],
  },
  {
    id: 6,
    kamId: 6,
    kam: 'Попова М.С.',
    programs: 2,
    activeInteractions: 2,
    completedInteractions: 2,
    overdueInteractions: 1,
    attentionRequired: 1,
    averageStageDuration: 4.6,
    programItems: [
      {
        id: 16,
        name: 'Промпт-инжиниринг',
        product: 'GigaChat',
      },
      {
        id: 17,
        name: 'Основы UX/UI-дизайна',
        product: 'Ростелеком Образование',
      },
    ],
    activeInteractionItems: [
      {
        id: 27,
        university: 'КФУ',
        program: 'Промпт-инжиниринг',
        stage: 'Обучение преподавателей',
      },
      {
        id: 28,
        university: 'БашГУ',
        program: 'Основы UX/UI-дизайна',
        stage: 'Первичная коммуникация',
      },
    ],
    completedInteractionItems: [
      {
        id: 29,
        university: 'УдГУ',
        program: 'Основы UX/UI-дизайна',
        stage: 'Ведение занятий',
      },
      {
        id: 30,
        university: 'КНИТУ',
        program: 'Промпт-инжиниринг',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 9,
        university: 'КФУ',
        program: 'Промпт-инжиниринг',
        stage: 'Обучение преподавателей',
        overdueDays: 2,
      },
    ],
    attentionItems: [
      {
        id: 11,
        university: 'КФУ',
        program: 'Промпт-инжиниринг',
        reason: 'Не завершено обучение преподавателей',
      },
    ],
  },
  {
    id: 7,
    kamId: 7,
    kam: 'Волков Р.Н.',
    programs: 4,
    activeInteractions: 4,
    completedInteractions: 3,
    overdueInteractions: 3,
    attentionRequired: 4,
    averageStageDuration: 7.2,
    programItems: [
      {
        id: 18,
        name: 'Специалист по анализу данных',
        product: 'Data Platform',
      },
      {
        id: 19,
        name: 'Анализ данных без программирования',
        product: 'Data Platform',
      },
      {
        id: 20,
        name: 'Python-разработчик с использованием инструментов ИИ',
        product: 'Ростелеком Лицей',
      },
      {
        id: 21,
        name: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        product: 'Ростелеком ИТ',
      },
    ],
    activeInteractionItems: [
      {
        id: 31,
        university: 'ДВФУ',
        program: 'Специалист по анализу данных',
        stage: 'Обмен документами',
      },
      {
        id: 32,
        university: 'СВФУ',
        program: 'Анализ данных без программирования',
        stage: 'Организация встречи',
      },
      {
        id: 33,
        university: 'ТГУ',
        program: 'Python-разработчик с использованием инструментов ИИ',
        stage: 'Актуализация программы',
      },
      {
        id: 34,
        university: 'НГУ',
        program: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        stage: 'Подписание документов',
      },
    ],
    completedInteractionItems: [
      {
        id: 35,
        university: 'СФУ',
        program: 'Специалист по анализу данных',
        stage: 'Ведение занятий',
      },
      {
        id: 36,
        university: 'ДВГУПС',
        program: 'Анализ данных без программирования',
        stage: 'Ведение занятий',
      },
      {
        id: 37,
        university: 'ИрНИТУ',
        program: 'Python-разработчик с использованием инструментов ИИ',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 10,
        university: 'ДВФУ',
        program: 'Специалист по анализу данных',
        stage: 'Обмен документами',
        overdueDays: 9,
      },
      {
        id: 11,
        university: 'СВФУ',
        program: 'Анализ данных без программирования',
        stage: 'Организация встречи',
        overdueDays: 6,
      },
      {
        id: 12,
        university: 'ТГУ',
        program: 'Python-разработчик с использованием инструментов ИИ',
        stage: 'Актуализация программы',
        overdueDays: 4,
      },
    ],
    attentionItems: [
      {
        id: 12,
        university: 'ДВФУ',
        program: 'Специалист по анализу данных',
        reason: 'Документы не согласованы в срок',
      },
      {
        id: 13,
        university: 'СВФУ',
        program: 'Анализ данных без программирования',
        reason: 'Встреча не назначена',
      },
      {
        id: 14,
        university: 'ТГУ',
        program: 'Python-разработчик с использованием инструментов ИИ',
        reason: 'Актуализация программы задерживается',
      },
      {
        id: 15,
        university: 'НГУ',
        program: 'Управление ИТ-проектами на базе программного продукта ПАО «Ростелеком»',
        reason: 'Документы ожидают подписания',
      },
    ],
  },
  {
    id: 8,
    kamId: 8,
    kam: 'Лебедев К.А.',
    programs: 2,
    activeInteractions: 3,
    completedInteractions: 2,
    overdueInteractions: 1,
    attentionRequired: 2,
    averageStageDuration: 5.1,
    programItems: [
      {
        id: 22,
        name: 'Веб-разработка на платформе «Акола»',
        product: 'Акола',
      },
      {
        id: 23,
        name: 'Инженер-тестировщик',
        product: 'Ростелеком ИТ',
      },
    ],
    activeInteractionItems: [
      {
        id: 38,
        university: 'МИРЭА',
        program: 'Веб-разработка на платформе «Акола»',
        stage: 'Передача материалов',
      },
      {
        id: 39,
        university: 'МАИ',
        program: 'Инженер-тестировщик',
        stage: 'Обучение преподавателей',
      },
      {
        id: 40,
        university: 'РТУ МИРЭА',
        program: 'Инженер-тестировщик',
        stage: 'Внедрение продукта',
      },
    ],
    completedInteractionItems: [
      {
        id: 41,
        university: 'ГУУ',
        program: 'Веб-разработка на платформе «Акола»',
        stage: 'Ведение занятий',
      },
      {
        id: 42,
        university: 'МЭИ',
        program: 'Инженер-тестировщик',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 13,
        university: 'МИРЭА',
        program: 'Веб-разработка на платформе «Акола»',
        stage: 'Передача материалов',
        overdueDays: 3,
      },
    ],
    attentionItems: [
      {
        id: 16,
        university: 'МИРЭА',
        program: 'Веб-разработка на платформе «Акола»',
        reason: 'Материалы не переданы в срок',
      },
      {
        id: 17,
        university: 'МАИ',
        program: 'Инженер-тестировщик',
        reason: 'Обучение преподавателей не завершено',
      },
    ],
  },
  {
    id: 9,
    kamId: 9,
    kam: 'Новикова А.П.',
    programs: 3,
    activeInteractions: 3,
    completedInteractions: 3,
    overdueInteractions: 1,
    attentionRequired: 2,
    averageStageDuration: 4.4,
    programItems: [
      {
        id: 24,
        name: 'Графический дизайн пользовательских интерфейсов',
        product: 'Ростелеком Образование',
      },
      {
        id: 25,
        name: 'Основы UX/UI-дизайна',
        product: 'Ростелеком Образование',
      },
      {
        id: 26,
        name: 'Промпт-инжиниринг',
        product: 'GigaChat',
      },
    ],
    activeInteractionItems: [
      {
        id: 43,
        university: 'РАНХиГС',
        program: 'Графический дизайн пользовательских интерфейсов',
        stage: 'Первичная коммуникация',
      },
      {
        id: 44,
        university: 'НИУ ВШЭ',
        program: 'Основы UX/UI-дизайна',
        stage: 'Обмен документами',
      },
      {
        id: 45,
        university: 'МГИМО',
        program: 'Промпт-инжиниринг',
        stage: 'Организация встречи',
      },
    ],
    completedInteractionItems: [
      {
        id: 46,
        university: 'Финансовый университет',
        program: 'Основы UX/UI-дизайна',
        stage: 'Ведение занятий',
      },
      {
        id: 47,
        university: 'РЭУ им. Г.В. Плеханова',
        program: 'Графический дизайн пользовательских интерфейсов',
        stage: 'Ведение занятий',
      },
      {
        id: 48,
        university: 'МГПУ',
        program: 'Промпт-инжиниринг',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 14,
        university: 'НИУ ВШЭ',
        program: 'Основы UX/UI-дизайна',
        stage: 'Обмен документами',
        overdueDays: 2,
      },
    ],
    attentionItems: [
      {
        id: 18,
        university: 'НИУ ВШЭ',
        program: 'Основы UX/UI-дизайна',
        reason: 'Согласование документов задерживается',
      },
      {
        id: 19,
        university: 'МГИМО',
        program: 'Промпт-инжиниринг',
        reason: 'Нет подтверждённой даты встречи',
      },
    ],
  },
  {
    id: 10,
    kamId: 10,
    kam: 'Макаров В.С.',
    programs: 3,
    activeInteractions: 4,
    completedInteractions: 2,
    overdueInteractions: 2,
    attentionRequired: 3,
    averageStageDuration: 6.1,
    programItems: [
      {
        id: 27,
        name: 'Введение в информационную безопасность',
        product: 'Solar',
      },
      {
        id: 28,
        name: 'DevOps-инженер с нуля',
        product: 'Cloud.ru',
      },
      {
        id: 29,
        name: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        product: 'Аврора',
      },
    ],
    activeInteractionItems: [
      {
        id: 49,
        university: 'ЮФУ',
        program: 'Введение в информационную безопасность',
        stage: 'Подписание документов',
      },
      {
        id: 50,
        university: 'КубГУ',
        program: 'DevOps-инженер с нуля',
        stage: 'Внедрение продукта',
      },
      {
        id: 51,
        university: 'СКФУ',
        program: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        stage: 'Обучение преподавателей',
      },
      {
        id: 52,
        university: 'ВолГУ',
        program: 'Введение в информационную безопасность',
        stage: 'Передача материалов',
      },
    ],
    completedInteractionItems: [
      {
        id: 53,
        university: 'ДГТУ',
        program: 'DevOps-инженер с нуля',
        stage: 'Ведение занятий',
      },
      {
        id: 54,
        university: 'КубГТУ',
        program: 'Введение в информационную безопасность',
        stage: 'Ведение занятий',
      },
    ],
    overdueItems: [
      {
        id: 15,
        university: 'КубГУ',
        program: 'DevOps-инженер с нуля',
        stage: 'Внедрение продукта',
        overdueDays: 5,
      },
      {
        id: 16,
        university: 'ВолГУ',
        program: 'Введение в информационную безопасность',
        stage: 'Передача материалов',
        overdueDays: 3,
      },
    ],
    attentionItems: [
      {
        id: 20,
        university: 'КубГУ',
        program: 'DevOps-инженер с нуля',
        reason: 'Внедрение продукта просрочено',
      },
      {
        id: 21,
        university: 'СКФУ',
        program: 'Создание мобильных приложений для ОС «Аврора» в фреймворке Qt Quick',
        reason: 'Обучение преподавателей идёт дольше планового срока',
      },
      {
        id: 22,
        university: 'ВолГУ',
        program: 'Введение в информационную безопасность',
        reason: 'Передача материалов задерживается',
      },
    ],
  },
];
