"""init crm schema

Revision ID: cade47f9d409
Revises: 
Create Date: 2026-09-17 16:31:46.354940

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'cade47f9d409'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('it_directions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_it_directions'))
    )
    op.create_table('universities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities'))
    )
    op.create_table('users',
    sa.Column('keycloak_user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_table('files',
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('storage_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_files_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_table('it_products',
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('documentation_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_it_products_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_it_products'))
    )
    op.create_table('it_programs',
    sa.Column('direction_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['it_directions.id'], name=op.f('fk_it_programs_direction_id_it_directions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_it_programs'))
    )
    op.create_table('university_contacts',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_university_contacts_university_id_universities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_university_contacts'))
    )
    op.create_table('workflow_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workflow_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_templates'))
    )
    op.create_table('program_products',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['it_products.id'], name=op.f('fk_program_products_product_id_it_products')),
    sa.ForeignKeyConstraint(['program_id'], ['it_programs.id'], name=op.f('fk_program_products_program_id_it_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_products')),
    sa.UniqueConstraint('program_id', 'product_id', name='uq_program_products_program_product')
    )
    op.create_table('university_interactions',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('manager_user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_template_id', sa.UUID(), nullable=True),
    sa.Column('current_stage_instance_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['users.id'], name=op.f('fk_university_interactions_manager_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['it_products.id'], name=op.f('fk_university_interactions_product_id_it_products')),
    sa.ForeignKeyConstraint(['program_id'], ['it_programs.id'], name=op.f('fk_university_interactions_program_id_it_programs')),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_university_interactions_university_id_universities')),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], name=op.f('fk_university_interactions_workflow_template_id_workflow_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_university_interactions'))
    )
    op.create_table('workflow_stages',
    sa.Column('workflow_template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_initial', sa.Boolean(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('default_duration_days', sa.Integer(), nullable=True),
    sa.Column('requires_comment', sa.Boolean(), nullable=False),
    sa.Column('requires_attachment', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_stages_workflow_template_id_workflow_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stages'))
    )
    op.create_table('contracts',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('contract_number', sa.String(length=128), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['university_interactions.id'], name=op.f('fk_contracts_interaction_id_university_interactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_table('interaction_contacts',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['university_contacts.id'], name=op.f('fk_interaction_contacts_contact_id_university_contacts')),
    sa.ForeignKeyConstraint(['interaction_id'], ['university_interactions.id'], name=op.f('fk_interaction_contacts_interaction_id_university_interactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_contacts')),
    sa.UniqueConstraint('interaction_id', 'contact_id', name='uq_interaction_contacts_interaction_contact')
    )
    op.create_table('workflow_stage_instances',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('workflow_stage_id', sa.UUID(), nullable=False),
    sa.Column('responsible_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['university_interactions.id'], name=op.f('fk_workflow_stage_instances_interaction_id_university_interactions')),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], name=op.f('fk_workflow_stage_instances_responsible_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_stage_id'], ['workflow_stages.id'], name=op.f('fk_workflow_stage_instances_workflow_stage_id_workflow_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stage_instances'))
    )
    op.create_foreign_key(
        'fk_university_interactions_current_stage_instance',
        'university_interactions',
        'workflow_stage_instances',
        ['current_stage_instance_id'],
        ['id'],
    )
    op.create_table('workflow_transitions',
    sa.Column('workflow_template_id', sa.UUID(), nullable=False),
    sa.Column('from_stage_id', sa.UUID(), nullable=False),
    sa.Column('to_stage_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('condition_code', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_id'], ['workflow_stages.id'], name=op.f('fk_workflow_transitions_from_stage_id_workflow_stages')),
    sa.ForeignKeyConstraint(['to_stage_id'], ['workflow_stages.id'], name=op.f('fk_workflow_transitions_to_stage_id_workflow_stages')),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_transitions_workflow_template_id_workflow_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transitions'))
    )
    op.create_table('licenses',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('license_number', sa.String(length=128), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_status', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name=op.f('fk_licenses_contract_id_contracts')),
    sa.ForeignKeyConstraint(['interaction_id'], ['university_interactions.id'], name=op.f('fk_licenses_interaction_id_university_interactions')),
    sa.ForeignKeyConstraint(['product_id'], ['it_products.id'], name=op.f('fk_licenses_product_id_it_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licenses'))
    )
    op.create_table('workflow_stage_attachments',
    sa.Column('stage_instance_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_workflow_stage_attachments_file_id_files')),
    sa.ForeignKeyConstraint(['stage_instance_id'], ['workflow_stage_instances.id'], name=op.f('fk_workflow_stage_attachments_stage_instance_id_workflow_stage_instances')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_workflow_stage_attachments_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stage_attachments'))
    )
    op.create_table('workflow_stage_comments',
    sa.Column('stage_instance_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_workflow_stage_comments_author_user_id_users')),
    sa.ForeignKeyConstraint(['stage_instance_id'], ['workflow_stage_instances.id'], name=op.f('fk_workflow_stage_comments_stage_instance_id_workflow_stage_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stage_comments'))
    )
    op.create_table('workflow_transition_history',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('from_stage_instance_id', sa.UUID(), nullable=True),
    sa.Column('to_stage_instance_id', sa.UUID(), nullable=True),
    sa.Column('transition_id', sa.UUID(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_stage_instance_id'], ['workflow_stage_instances.id'], name=op.f('fk_workflow_transition_history_from_stage_instance_id_workflow_stage_instances')),
    sa.ForeignKeyConstraint(['interaction_id'], ['university_interactions.id'], name=op.f('fk_workflow_transition_history_interaction_id_university_interactions')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_workflow_transition_history_performed_by_users')),
    sa.ForeignKeyConstraint(['to_stage_instance_id'], ['workflow_stage_instances.id'], name=op.f('fk_workflow_transition_history_to_stage_instance_id_workflow_stage_instances')),
    sa.ForeignKeyConstraint(['transition_id'], ['workflow_transitions.id'], name=op.f('fk_workflow_transition_history_transition_id_workflow_transitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transition_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_university_interactions_current_stage_instance',
        'university_interactions',
        type_='foreignkey',
    )
    op.drop_table('workflow_transition_history')
    op.drop_table('workflow_stage_comments')
    op.drop_table('workflow_stage_attachments')
    op.drop_table('licenses')
    op.drop_table('workflow_transitions')
    op.drop_table('workflow_stage_instances')
    op.drop_table('interaction_contacts')
    op.drop_table('contracts')
    op.drop_table('workflow_stages')
    op.drop_table('university_interactions')
    op.drop_table('program_products')
    op.drop_table('workflow_templates')
    op.drop_table('university_contacts')
    op.drop_table('it_programs')
    op.drop_table('it_products')
    op.drop_table('files')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('universities')
    op.drop_table('it_directions')
    # ### end Alembic commands ###
